export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Customer } from "./Customer/Customer";
export { default as Farmer } from "./Farmer/Farmer";
export { default as InwardData } from "./Farmer/InwardData";
export { default as OutwardData } from "./Farmer/OutwardData";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Admin } from "./Admin/Admin";