import {
  GRANDEUR,
  MORECORNER,
  KHARADI,
  GODREJ,
  AMANORA,
  AMBEGAON,
  BHAVANINAGAR,
  BRAMHASUNCITY,
  FPLAZA,
  GODREJHORIZON,
  HADPSAR,
  IVYESTATE,
  KARVENAGAR,
  TINGRENAGAR,
  MAGARPATTA,
} from '../../assets/images/markets'

export const marketImageMap = {
  'More Corner': MORECORNER,
  'Ivy Estate': IVYESTATE,
  'Kharadi IT Park': KHARADI,
  'Karve Nagar': KARVENAGAR,
  'Godrej Prana': GODREJ,
  'Godrej Horizon': GODREJHORIZON,
  'Bhavadi Road': BHAVANINAGAR,
  'Bramhasun City': BRAMHASUNCITY,
  Magarpatta: MAGARPATTA,
  'Amanora City': AMANORA,
  'Grandeur Undri': GRANDEUR,
  'Tingre Nagar': TINGRENAGAR,
  'F-Plaza': FPLAZA,
  Ambegaon: AMBEGAON,
  Hadpsar: HADPSAR,
}
