import {
  GRANDEUR,
  MORECORNER,
  KHARADIITPARK,
  GODREJ,
  AMANORA,
  AMBEGAON,
  BHAVADIROAD,
  BRAMHASUNCITY,
  HANDEWADI,
  GODREJHORIZON,
  HADPSAR,
  IVYESTATE,
  KARVENAGAR,
  TINGRENAGAR,
  MAGARPATTA,
} from '../../assets/images/markets'

export const marketImageMap = {
  'More Corner': MORECORNER,
  'Ivy Estate': IVYESTATE,
  'Kharadi IT Park': KHARADIITPARK,
  'Karve Nagar': KARVENAGAR,
  'Godrej Prana': GODREJ,
  'Godrej Horizon': GODREJHORIZON,
  'Bhavadi Road': BHAVADIROAD,
  'Bramhasun City': BRAMHASUNCITY,
  'Magarpatta': MAGARPATTA,
  'Amanora City': AMANORA,
  'Grandeur Undri': GRANDEUR,
  'Tingre Nagar': TINGRENAGAR,
  'Handewadi': HANDEWADI,
  'Ambegaon': AMBEGAON,
  'Hadpsar': HADPSAR,
}
