export const commodity = [
  // Leaves
  { label: 'Amaranthus' },
  { label: 'Beet Root' },
  { label: 'Chukka- sorrel Leaves' },
  { label: 'Colocasia Leaves' },
  { label: 'Curry Leaves' },
  { label: 'Dill' },
  { label: 'Fenugreek Leaves' },
  { label: 'Green Amaranth' },
  { label: 'Spinach' },
  { label: 'Spring Onion' },
  { label: 'Sufflower' },

  // Wild-Antic
  { label: 'Chilli' },
  { label: 'Colocasia Roots' },
  { label: 'Cucumber Madras' },
  { label: 'Kohlrabi' },
  { label: 'Onion White-Pandhara Kanda' },
  { label: 'Pointed Gourd' },
  { label: 'Pumpkin' },
  { label: 'Raw Jackfruit' },
  { label: 'Raw Papaya' },
  { label: 'Sambhar Kanda' },
  { label: 'Snake Gourd' },
  { label: 'Spiny Gourd' },
  { label: 'Sweet Potato' },
  { label: 'Yam' },

  // Exotic
  { label: 'Asparagus' },
  { label: 'Avocado' },
  { label: 'Baby Corn' },
  { label: 'Baby Potato' },
  { label: 'Basil' },
  { label: 'Broccoli' },
  { label: 'Celery' },
  { label: 'Cherry Tomato' },
  { label: 'Chinese Cabbage' },
  { label: 'Coccinia' },
  { label: 'Green Zucchini' },
  { label: 'Iceberg Lettuce' },
  { label: 'Parsley' },
  { label: 'Red Cabbage' },
  { label: 'Red Capsicum' },
  { label: 'Romaine Lettuce' },
  { label: 'Yellow Capsicum' },
  { label: 'Yellow Zucchini' },
  { label: 'Mushroom' },
  { label: 'Sweet Corn' },
  { label: 'Sweet Corn Grains' },

  // Special stall
  { label: 'Cabbage' },
  { label: 'Potato (Agra' },
  { label: 'Potato (Indore' },
  { label: 'Potato (Talegav' },

  // Fruit Vegetables
  { label: 'Beans Double' },
  { label: 'Bitter Gourd' },
  { label: 'Brinjal Big' },
  { label: 'Brinjal Green' },
  { label: 'Brinjal Long Green' },
  { label: 'Brinjal Purple' },
  { label: 'Carrot' },
  { label: 'Cauliflower' },
  { label: 'Chavali Beans' },
  { label: 'Chickpeas - Chana sprouts' },
  { label: 'Chilli - Bhavgagari Mirchi' },
  { label: 'Chilli Green' },
  { label: 'Chilli Simple' },
  { label: 'Cluster Beans' },
  { label: 'Coconut' },
  { label: 'Colocasia Roots' },
  { label: 'Coriander' },
  { label: 'Cucumber' },
  { label: 'Cucumber Madras' },
  { label: 'Cucumber Madras- Sambar Kakadi' },
  { label: 'Cucumber Polyhouse- English Kakadi' },
  { label: 'Drum Sticks' },
  { label: 'Field Beans' },
  { label: 'Fresh Peeled Green Peas' },
  { label: 'Garlic' },
  { label: 'Ginger' },
  { label: 'Green Capsicum' },
  { label: 'Green Mango' },
  { label: 'Green Peas' },
  { label: 'Groundnut Pods' },
  { label: 'Tamarind' },
  { label: 'Lady Finger' },
  { label: 'Lemon Grass' },
  { label: 'Mint' },
  { label: 'Onion' },
  { label: 'Onion Sambhar' },
  { label: 'Lima Beans' },
  { label: 'Peeled Garlic' },
  { label: 'Potato' },
  { label: 'Radish' },
  { label: 'Ridgegourd' },
  { label: 'Sponge Gourd' },
  { label: 'Tomato' },
  { label: 'Wal' },
  { label: 'Wal Broad' },
  { label: 'Wal Surati' },
  { label: 'Water Chestnuts' },

  // Fruit Export
  { label: 'Apple Fuji' },
  { label: 'Apple Green' },
  { label: 'Apple Kinnaur' },
  { label: 'Apple Red Delicious' },
  { label: 'Apple Shimla Big' },
  { label: 'Kiwi' },
  { label: 'Litchi' },
  { label: 'Strawberry' },

  // Fruit Summer
  { label: 'Grapes Black' },
  { label: 'Grapes Green' },
  { label: 'Jambhul' },
  { label: 'Mango Badami (For Juice' },
  { label: 'Mango Devgad Hapus' },
  { label: 'Mango Keshar' },
  { label: 'Mango Lalbag' },
  { label: 'Mango Payri' },
  { label: 'Mango Ratnagiri Hapus' },
  { label: 'Mango Totapuri' },
  { label: 'Muskmelon' },
  { label: 'Watermelon Kiran' },
  { label: 'Watermelon Regular' },

  // Fruit
  { label: 'Amla' },
  { label: 'Apple Gourd' },
  { label: 'Ashgourd' },
  { label: 'Banana' },
  { label: 'Custard-apple' },
  { label: 'Elaichi Banana' },
  { label: 'Figs' },
  { label: 'Guava' },
  { label: 'Jackfruit Peeled' },
  { label: 'Jujube - Ber' },
  { label: 'Orange Small' },
  { label: 'Orange Kinnow' },
  { label: 'Papaya' },
  { label: 'Pear Imported' },
  { label: 'Pomogranate' },
  { label: 'Raw Banana' },
  { label: 'Sapodilla' },
  { label: 'Sugarcane' },
  { label: 'Sweet Lime' },
  { label: 'Tender' },
]
