export const marketData = [
  {
    day: 'tuesday',
    name: 'karve Nagar',
    location: 'https://goo.gl/maps/5sETcJGzXWoXC5SG9',
    address: 'karveNagarLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'tuesday',
    name: 'godrejPrana',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'godrejPranaLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'tuesday',
    name: 'wadgaonSheri',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'wadgaonSheriLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'wednesday',
    name: 'hadapsar',
    location: 'https://maps.app.goo.gl/bh7wNdiyVWcvy15p9?g_st=iw',
    address: 'hadapsarLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'wednesday',
    name: 'undri',
    location: 'https://goo.gl/maps/GWympTKEp5Jqj8EB7',
    address: 'undriLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'thursday',
    name: 'kharadi',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'kharadiLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'thursday',
    name: 'nottingHill',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'nottingHillLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'friday',
    name: 'wagholi',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'dabhadeChowkwagholiLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'friday',
    name: 'wadgaonSheri',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'vadgoanSheriLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'saturday',
    name: 'adityaNandanvan',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'adityaNandanvanLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'saturday',
    name: 'wadachiWadi',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'wadachiWadiLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'saturday',
    name: 'wagholi',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'dabhadeChowkwagholiLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'sunday',
    name: 'magarpatta',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'magarpattaLocation',
    time: '7AM - 1PM',
  },
  {
    day: 'sunday',
    name: 'sadeSatraNali',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'sadeSatraNaliLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'sunday',
    name: 'ivyEstateWagholi',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'ivyEstateWagholiLocation',
    time: '3PM - 9PM',
  },
  {
    day: 'sunday',
    name: 'nottingHill',
    location: 'https://maps.app.goo.gl/hWAwbDk3smxX7wfn9?g_st=iw',
    address: 'nottingHillLocation',
    time: '3PM - 9PM',
  },
]
