export const INIT_FARMER = 'INIT_FARMER'

export const FETCH_FARMER_LIST = {
  START: 'FETCH_FARMER_LIST_START',
  SUCCESS: 'FETCH_FARMER_LIST_SUCCESS',
  ERROR: 'FETCH_FARMER_LIST_ERROR',
}

export const FETCH_FARMER_RECORD = {
  START: 'FETCH_FARMER_RECORD_START',
  SUCCESS: 'FETCH_FARMER_RECORD_SUCCESS',
  ERROR: 'FETCH_FARMER_RECORD_ERROR',
}

export const INIT_CUSTOMER = 'INIT_CUSTOMER'

export const FETCH_CUSTOMER_LIST = {
  START: 'FETCH_CUSTOMER_LIST_START',
  SUCCESS: 'FETCH_CUSTOMER_LIST_SUCCESS',
  ERROR: 'FETCH_CUSTOMER_LIST_ERROR',
}

export const FETCH_CUSTOMER_RECORD = {
  START: 'FETCH_CUSTOMER_RECORD_START',
  SUCCESS: 'FETCH_CUSTOMER_RECORD_SUCCESS',
  ERROR: 'FETCH_CUSTOMER_RECORD_ERROR',
}

export const INIT_CANCELLED_STALLS = 'INIT_CANCELLED_STALLS'

export const FETCH_CANCELLED_STALLS_LIST = {
  START: 'FETCH_CANCELLED_STALLS_LIST_START',
  SUCCESS: 'FETCH_CANCELLED_STALLS_LIST_SUCCESS',
  ERROR: 'FETCH_CANCELLED_STALLS_LIST_ERROR',
}

export const FETCH_CANCELLED_STALLS_RECORD = {
  START: 'FETCH_CANCELLED_STALLS_RECORD_START',
  SUCCESS: 'FETCH_CANCELLED_STALLS_RECORD_SUCCESS',
  ERROR: 'FETCH_CANCELLED_STALLS_RECORD_ERROR',
}
