export const INIT_LOGIN = 'INIT_LOGIN'
export const INIT_REGISTRATION = 'INIT_REGISTRATION'
export const INIT_VERIFICATION = 'INIT_VERIFICATION'
export const LOGIN = {
  START: 'LOGIN_START',
  SUCCESS: 'LOGIN_SUCCESS',
  ERROR: 'LOGIN_ERROR',
}
export const LOGOUT = {
  START: 'LOGOUT_START',
  SUCCESS: 'LOGOUT_SUCCESS',
  ERROR: 'LOGOUT_ERROR',
}

export const REGISTER = {
  START: 'REGISTER_START',
  SUCCESS: 'REGISTER_SUCCESS',
  ERROR: 'REGISTER_ERROR',
}

export const SEND_VERIFICATION_CODE = {
  START: 'SEND_VERIFICATION_CODE_START',
  SUCCESS: 'SEND_VERIFICATION_CODE_SUCCESS',
  ERROR: 'SEND_VERIFICATION_CODE_ERROR',
}

export const RESEND_VERIFICATION_CODE = {
  START: 'RESEND_VERIFICATION_CODE_START',
  SUCCESS: 'RESEND_VERIFICATION_CODE_SUCCESS',
  ERROR: 'RESEND_VERIFICATION_CODE_ERROR',
}

export const VERIFY_CODE = {
  START: 'VERIFY_CODE_START',
  SUCCESS: 'VERIFY_CODE_SUCCESS',
  ERROR: 'VERIFY_CODE_ERROR',
}
