export const FETCH_MARKET_LIST = {
  START: 'FETCH_MARKET_LIST_START',
  SUCCESS: 'FETCH_MARKET_LIST_SUCCESS',
  ERROR: 'FETCH_MARKET_LIST_ERROR',
}

export const FETCH_MARKET_RECORD = {
  START: 'FETCH_MARKET_RECORD_START',
  SUCCESS: 'FETCH_MARKET_RECORD_SUCCESS',
  ERROR: 'FETCH_MARKET_RECORD_ERROR',
}

export const INIT_MARKET = 'INIT_MARKET'
