export const INIT_STALL = 'INIT_STALL'

export const FETCH_STALL_LIST = {
  START: 'FETCH_STALL_START',
  SUCCESS: 'FETCH_STALL_SUCCESS',
  ERROR: 'FETCH_STALL_ERROR',
}

export const FETCH_STALL_RECORD = {
  START: 'FETCH_STALL_RECORD_START',
  SUCCESS: 'FETCH_STALL_RECORD_SUCCESS',
  ERROR: 'FETCH_STALL_RECORD_ERROR',
}

export const CREATE_STALL_RECORD = {
  START: 'CREATE_STALL_RECORD_START',
  SUCCESS: 'CREATE_STALL_RECORD_SUCCESS',
  ERROR: 'CREATE_STALL_RECORD_ERROR',
}
export const UPDATE_STALL_RECORD = {
  START: 'UPDATE_STALL_RECORD_START',
  SUCCESS: 'UPDATE_STALL_RECORD_SUCCESS',
  ERROR: 'UPDATE_STALL_RECORD_ERROR',
}

export const DELETE_STALL = {
  START: 'DELETE_STALL_START',
  SUCCESS: 'DELETE_STALL_SUCCESS',
  ERROR: 'DELETE_STALL_ERROR',
}

export const SELECT_STALL = 'SELECT_STALL'

export const FETCH_BOOKED_STALL_LIST = {
  START: 'FETCH_BOOKED_STALL_LIST_START',
  SUCCESS: 'FETCH_BOOKED_STALL_LIST_SUCCESS',
  ERROR: 'FETCH_BOOKED_STALL_LIST_ERROR',
}

export const FETCH_BOOKED_STALL_LIST_BY_USER = {
  START: 'FETCH_BOOKED_STALL_LIST_BY_USER_START',
  SUCCESS: 'FETCH_BOOKED_STALL_LIST_BY_USER_SUCCESS',
  ERROR: 'FETCH_BOOKED_STALL_LIST_BY_USER_ERROR',
}

export const UPDATE_SELECTED_STALLS = {
  SUCCESS: 'UPDATE_SELECTED_STALLS_SUCCESS',
}
