export const INIT_STALL_BOOKING = "INIT_STALL_BOOKING";

export const FETCH_STALL_BOOKING_LIST = {
  START: "FETCH_STALL_BOOKING_LIST_START",
  SUCCESS: "FETCH_STALL_BOOKING_LIST_SUCCESS",
  ERROR: "FETCH_STALL_BOOKING_LIST_ERROR",
};
export const FETCH_STALL_BOOKING_RECORD_BY_ID = {
  START: "FETCH_STALL_BOOKING_RECORD_BY_ID_START",
  SUCCESS: "FETCH_STALL_BOOKING_RECORD_BY_ID_SUCCESS",
  ERROR: "FETCH_STALL_BOOKING_RECORD_BY_ID_ERROR",
};

export const CREATE_STALL_BOOKING = {
  START: "CREATE_STALL_BOOKING_START",
  SUCCESS: "CREATE_STALL_BOOKING_SUCCESS",
  ERROR: "CREATE_STALL_BOOKING_ERROR",
};

export const FETCH_STALL_BOOKING_RECORD_BY_MARKET = {
  START: "FETCH_STALL_BOOKING_RECORD_BY_MARKET_START",
  SUCCESS: "FETCH_STALL_BOOKING_RECORD_BY_MARKET_SUCCESS",
  ERROR: "FETCH_STALL_BOOKING_RECORD_BY_MARKET_ERROR",
};
export const FETCH_STALL_BOOKING_LIST_BY_USER = {
  START: "FETCH_STALL_BOOKING_LIST_BY_USER_START",
  SUCCESS: "FETCH_STALL_BOOKING_LIST_BY_USER_SUCCESS",
  ERROR: "FETCH_STALL_BOOKING_LIST_BY_USER_ERROR",
};
