export const INIT_STALL = "INIT_STALL";

export const FETCH_STALL_LIST = {
  START: "FETCH_STALL_LIST_START",
  SUCCESS: "FETCH_STALL_LIST_SUCCESS",
  ERROR: "FETCH_STALL_LIST_ERROR",
};

export const FETCH_STALL_RECORD_BY_ID = {
  START: "FETCH_STALL_RECORD_BY_ID_START",
  SUCCESS: "FETCH_STALL_RECORD_BY_ID_SUCCESS",
  ERROR: "FETCH_STALL_RECORD_BY_ID_ERROR",
};

export const FETCH_STALL_RECORD_BY_MARKET = {
  START: "FETCH_STALL_RECORD_BY_MARKET_START",
  SUCCESS: "FETCH_STALL_RECORD_BY_MARKET_SUCCESS",
  ERROR: "FETCH_STALL_RECORD_BY_MARKET_ERROR",
};
