export const INIT_STALL_BOOKING = 'INIT_STALL_BOOKING'

export const FETCH_STALL_BOOKING_LIST = {
  START: 'FETCH_STALL_BOOKING_START',
  SUCCESS: 'FETCH_STALL_BOOKING_SUCCESS',
  ERROR: 'FETCH_STALL_BOOKING_ERROR',
}

export const FETCH_STALL_BOOKING_RECORD = {
  START: 'FETCH_STALL_BOOKING_RECORD_START',
  SUCCESS: 'FETCH_STALL_BOOKING_RECORD_SUCCESS',
  ERROR: 'FETCH_STALL_BOOKING_RECORD_ERROR',
}

export const CREATE_STALL_BOOKING_RECORD = {
  START: 'CREATE_STALL_BOOKING_RECORD_START',
  SUCCESS: 'CREATE_STALL_BOOKING_RECORD_SUCCESS',
  ERROR: 'CREATE_STALL_BOOKING_RECORD_ERROR',
}
export const UPDATE_STALL_BOOKING_RECORD = {
  START: 'UPDATE_STALL_BOOKING_RECORD_START',
  SUCCESS: 'UPDATE_STALL_BOOKING_RECORD_SUCCESS',
  ERROR: 'UPDATE_STALL_BOOKING_RECORD_ERROR',
}

export const DELETE_STALL_BOOKING = {
  START: 'DELETE_STALL_BOOKING_START',
  SUCCESS: 'DELETE_STALL_BOOKING_SUCCESS',
  ERROR: 'DELETE_STALL_BOOKING_ERROR',
}

export const CREATE_MILTIPLE_STALL_BOOKING_RECORD = {
  START: 'CREATE_MILTIPLE_STALL_BOOKING_RECORD_START',
  SUCCESS: 'CREATE_MILTIPLE_STALL_BOOKING_RECORD_SUCCESS',
  ERROR: 'CREATE_MILTIPLE_STALL_BOOKING_RECORD_ERROR',
}
